<?php

namespace FileD\FileBundle\Entity;

use FileD\FileBundle\Entity\FileRepository;

/**
 * DirectoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @author epidoux <eric.pidoux@gmail.com>
 * @version 1.0
 */
class DirectoryRepository extends FileRepository
{

	/**
	 * Find directories which have the given user shared and the given parent file
	 * @param User the user
	 * @param File the parent file
	 * @return the files
	 */
	public function findDirectoriesShared($user,$parent)
	{
	    $query ="SELECT
		            d
		        FROM FileDFileBundle:Directory d
				JOIN d.usersShare u 
				WHERE u.id = :id
		        ";
	    if($parent!=null)$query.=" AND d.parent =:parent";
	    $query.=" ORDER BY d.name ASC";
		$query = $this->_em->createQuery($query)
				    ->setParameter('id', $user->getId());
		if($parent !=null)$query->setParameter('parent', $parent);
				    
		return $query->getResult();
	}
}
