<?php

namespace FileD\FileBundle\Entity;

use FileD\FileBundle\Entity\FileRepository;

/**
 * DirectoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @author epidoux <eric.pidoux@gmail.com>
 * @version 1.0
 */
class DirectoryRepository extends FileRepository
{
}
