<?php

namespace FileD\FileBundle\Entity;

use FileD\FileBundle\Entity\FileRepository;

/**
 * DirectoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectoryRepository extends FileRepository
{
}
