<?php

namespace FileD\FileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{


	/**
	 * Find file by path
	 * @param $path the path to match
	 * @return the entity
	 */
	public function findIdByPath($path)
	{
		$result = $this->_em->createQuery('
		        SELECT
		            f.id
		        FROM
		            FileDFileBundle:File f
		        WHERE
		            f.link = :link
		    ')
			    ->setParameter('link', $path)
				->getResult();
		$id = null;
		if(count($result) > 0)
		{
			$id=$result[0]['id'];
		}
		return $id;
	}
}
